# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#


# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:

  - Name: Org1
    Domain: org1.cathaybc.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - "127.0.0.1"
      Start: 1
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.cathaybc.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - "127.0.0.1"
      Start: 2
    Users:
      Count: 1

  - Name: Org3
    Domain: org3.cathaybc.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - "127.0.0.1"
      Start: 3
    Users:
      Count: 1